---
title: "Tarea Clase 01 septiembre"
description: |
  Tarea de la clase del día 01 de septiembre del curso ICP5006-1 sobre gráficos exploratorios.
author:
  - name: Ines Pereira
    url: https://example.com/norajones
    affiliation: Spacely Sprockets
    affiliation_url: https://example.com/spacelysprokets
date: 2022-09-23
output:
  distill::distill_article:
    self_contained: false
---

### Base de datos

```{r}
#open database
vdem <- readRDS("vdem.rds")
library(tidyverse)
#install.packages('sjmisc')
library(sjmisc)
#install.packages('kableExtra')
library(kableExtra)

#subset
vdem_subset <- vdem %>% 
  select(country_name, v2x_partipdem, 
         v2x_cspart, v2elmulpar, v2psprlnks, e_peedgini, 
         e_regionpol, e_gdppc, e_pop) %>% 
  group_by(country_name) %>% 
  summarise_all(function(x)  mean(x, na.rm = T))
```
### Histograma

```{r}
#dependent variable
vdem_subset %>% 
  ggplot(aes(x = v2x_cspart, na.rm = T)) +
  geom_histogram(binwidth = 0.05) +
  labs(x = "Participación de las personas en OSC [0-1] ", y = "Frecuencia",
       title = "Distribución de la variable dependiente",
       caption = "Fuente: Varieties of Democracy")

#independent variable
vdem_subset %>% 
  ggplot(aes(x = e_peedgini, na.rm = T)) +
  geom_histogram(binwidth = 2.5) +
  labs(x = "Coeficiente de Gini de desigualdad educacional", y = "Frecuencia",
       title = "Distribución de la variable independiente",
       caption = "Fuente: Varieties of Democracy")
```
### Gráfico de barras

```{r}
vdem_subset %>% 
  ggplot(aes(x=e_regionpol)) +
  geom_bar(color="blue", fill="white") +
  labs(x = "Clasificación regional", y = "Frecuencia",
       title = "Clasificación regional de los países basados en su posición política-geográfica",
       caption = "Fuente: Varieties of Democracy")
```
### Boxplot

```{r}
vdem_subset %>% 
  ggplot(aes(x=factor(e_regionpol), y = v2psprlnks	))+
  geom_boxplot( color="cadetblue", fill="steelblue", alpha = 0.5) +
  theme_minimal() +
  labs(x = "Clasificacion Regional", y = "Forma de vínculo",
       title = "Distribuicion de la forma de vínculo dos partidos y votantes por Clasificacion Regional",
       caption = "Fuente: Varieties of Democracy")
```
### Scatterplot

```{r}
vdem_subset %>% 
ggplot(aes(x=e_peedgini, y=v2x_cspart)) +
  geom_point(color="cadetblue", size=2, shape=23) + 
  labs(x = "Inequidad educacional", y = "Participación de las personas en OSC ",
       title = "Relacion entre la Inequidad educacional y la Participación de las personas en OSC",
       caption = "Fuente: Varieties of Democracy")
```