---
title: "Tarea Clase 06 octubre"
description: |
  Tarea de la clase del día 06 de octubre del curso ICP5006-1 sobre variables latentes.
author:
  - name: Ines Pereira
    url: https://example.com/norajones
    affiliation: Spacely Sprockets
    affiliation_url: https://example.com/spacelysprokets
date: 2022-10-19
output:
  distill::distill_article:
    self_contained: false
---

## Proyecto de Investigación

Impacto de los cambios de los componentes ópticos oculares en la refracción de los jóvenes

### Introducción

Una variable latente es una variable que no se puede observar. Sin embargo, la presencia de variables latentes puede detectarse por sus efectos sobre las variables observables.

Así, las variables latentes son variables que sólo pueden inferirse indirectamente a través de un modelo a partir de otras variables observables, que pueden observarse o medirse directamente.

A continuación, se exploran dos ejemplos de variables latentes presentes en este proyecto de investigación.

### Caso 1

* **Variable Latente**\
  + M: Graduación de una persona determinada en su componente esférica\

* **Variables observadas**\
  + Esf: Valor de la esfera de la refracción convencional\
  + Cil: Valor del cilindro de la refracción convencional\
  + α: Valor del eje de la refracción convencional\

* **Modelo**\
    M = Esf + Cil/2\
    J0 = -Cil x cos (2 α)/2\
    J45 = -Cil x sin (2 α)/2\

### Caso 2

* **Variable Latente**\
  + orient_astigm: Orientación del astigmatismo\

* **Variable observada**\
  + α: Valor del eje de la refracción convencional\

* **Modelo**\
    α < 20.01            ->  orient_astigm = 1\
    20.01 < α < 70       ->  orient_astigm = 2\
    70 < α < 110.011     ->  orient_astigm = 3\
    110.011 < α <159.99  ->  orient_astigm = 2\
    159.99 < α < 181     ->  orient_astigm = 1\


