---
title: "Entrega IV - Impacto de los cambios de los componentes ópticos oculares en la refracción de los jóvenes"
description: |
  En este post se presentan la discusión de los resultados y las conclusiones de este proyecto de investigación.
author:
  - name: Ines Pereira
    url: https://example.com/norajones
    affiliation: Spacely Sprockets
    affiliation_url: https://example.com/spacelysprokets
date: 2022-12-03
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Importancia del tema de investigación 

Este proyecto de investigación tenía como objetivo estudiar el impacto de los cambios de los componentes ópticos oculares, como la longitud axial del ojo y el radio de curvatura, en la refracción de los jóvenes. Para eso se definió como hipótesis que la graduación de una persona determinada en su componente esférica (M) cambia con la longitud axial del ojo (CA) y el radio de curvatura (RC). 

Comprender los cambios en los componentes ópticos y cómo se relacionan con la graduación de las personas es muy importante no sólo para efectos optométricos, sino también para la salud ocular de las personas. Poder predecir la graduación que tendrán las personas, al cambiar el estado de sus ojos, permite predecir su estado visual (miopía, hipermetropía o emetropía) y así prevenir su progresión. Este análisis y prevención son especialmente importantes cuando hablamos de la progresión de la miopía, ya que puede derivar en enfermedades oculares graves. Así, controlar la progresión de la miopía es muy importante y una de las principales preocupaciones en el campo de la óptica, especialmente entre los jóvenes, un grupo de edad en el que se produce un mayor cambio en sus componentes ópticos y para que se puedan prevenir futuros problemas. De este modo, se realizó este estudio en el que se  efectuaron mediciones de diferentes valores de elementos ópticos, centrándose en niños y jóvenes.

## Discusión de los resultados

Después de procesar los datos y analizar los resultados, se llegó a la conclusión de que la longitud axial del ojo y el radio de curvatura tienen un impacto significativo en la graduación obtenida y son determinantes de la condición visual adquirida por las personas. Además, se destaca que la longitud axial del ojo disminuye la graduación de una persona, lo que es equivalente al aumento de la miopía, o sea, cuanto mayor es la longitud axial del ojo, más severa es la miopía. Este es un resultado importante para el control de la progresión de la miopía en los jóvenes.  

En cuanto a la incidencia de factores, como la edad y el sexo, aunque se comprobó, mediante los gráficos de dispersión, una tendencia al aumento de la longitud con la edad, hasta una determinada edad, los resultados obtenidos en los modelos de regresion no mostraron una relación significativa. En los modelos de regresión, se ha determinado que estos factores no tienen un impacto significativo en la graduación de las personas, lo que es un resultado diferente a lo demostrado en otros estudios.

Esta diferencia en los resultados puede derivarse de las limitaciones de este proyecto de investigación y, por tanto, estar asociada a dos factores inherentes a este estudio. El primer factor está relacionado con la naturaleza de los datos, ya que las personas que participaron en el estudio son en su mayoría jóvenes, por lo que las edades estudiadas no cubren todo el espectro de la población y estos resultados no pueden extrapolarse. Sin embargo, este no era el objetivo principal de este estudio, ya que se trataba de evaluar el impacto en los jóvenes. El segundo factor se refiere a la metodología utilizada en el estudio, que se basa en mediciones únicas y puntuales de las variables de estudio, lo que significa que no existen datos en diferentes circunstancias y momentos temporales distintos que nos permitan mostrar una evolución de los resultados y, así, poder concluir sobre cambios y progresión en el tiempo.

## Recomendaciones futuras

Así, como se han señalado algunas limitaciones de este estudio, se recomienda realizar algunas adaptaciones y mejoras para obtener resultados más significativos y válidos, que permitan extraer conclusiones más profundas sobre el impacto de los componentes ópticos en la refracción. De este modo, se recomienda realizar varias mediciones en las mismas personas, en distintos momentos, para poder seguir los cambios en los distintos componentes ópticos y concluir los efectos sobre la graduación. Además, para evaluar los resultados sobre el efecto de la edad, se recomienda un estudio más exhaustivo que incluya diferentes grupos de edad.

## Conclusión

Finalmente, con este estudio fue posible obtener resultados significativos que permitieran corroborar la hipótesis planteada y evaluar el impacto de los cambios en los componentes ópticos sobre la visión de los jóvenes. Sin embargo, se detectaron algunas limitaciones que deberían explorarse en futuros estudios para profundizar en esta área de estudio.



